cabal-version: 2.4
name: nix-sakuin
version: 0.1.0.0
license: MIT
copyright: 2026 Meowcolm024
author: Meowcolm024
extra-source-files:
  LICENSE
  README.md
  test/assets/5a5lrqlgqqhfd02lp7l8gqdypcckxiqd.ls
  test/assets/5a5lrqlgqqhfd02lp7l8gqdypcckxiqd.narinfo
  test/assets/packages.json

common shared
  ghc-options:
    -Wall
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-deriving-strategies
    -Wunused-foralls
    -Wunused-imports
    -fprint-explicit-foralls
    -fprint-explicit-kinds
    -Werror

  default-extensions:
    ApplicativeDo
    DataKinds
    DerivingStrategies
    DerivingVia
    GADTs
    LambdaCase
    MultiWayIf
    NoStarIsType
    OverloadedStrings
    StrictData
    TypeFamilies
    ViewPatterns

  build-depends:
    aeson,
    base >=4 && <5,
    brotli,
    bytestring,
    containers,
    data-default,
    directory,
    effectful,
    http-client,
    http-client-tls,
    http-types,
    lzma,
    network-uri,
    optparse-applicative,
    path,
    path-io,
    random,
    regex-tdfa,
    text,
    typed-process,
    zstd,

  default-language: GHC2021

library
  import: shared
  hs-source-dirs: src
  exposed-modules:
    Sakuin
    Sakuin.Database
    Sakuin.Database.MemoryDatabase
    Sakuin.Hydra
    Sakuin.NixEnv
    Sakuin.Pipeline
    Sakuin.Progress
    Sakuin.Types
    Sakuin.WorkQueue

executable nix-sakuin
  import: shared
  hs-source-dirs: app
  main-is: Main.hs
  build-depends:
    nix-sakuin

  autogen-modules:
    Paths_nix_sakuin

  other-modules:
    Cli
    Index
    Locate
    Paths_nix_sakuin

  ghc-options:
    -O2
    -threaded
    -rtsopts
    -with-rtsopts=-N
    -funbox-strict-fields

test-suite nix-sakuin-test
  import: shared
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  hs-source-dirs:
    test

  other-modules:
    Sakuin.DatabaseSpec
    Sakuin.HydraSpec
    Sakuin.MockRegistry
    Sakuin.MockRegistrySpec
    Sakuin.NixEnvSpec
    Sakuin.PipelineSpec
    Sakuin.TypesSpec

  build-depends:
    nix-sakuin,
    tasty,
    tasty-hunit,
